### ISSUE TITLE
OBS triggering

### ISSUE THREAD

**Issue by pkej** [TuomoKu/SPX-GC#10]
How would I load a project, rundown and trigger one or more templates from OBS/Streamdeck for full automation?

**Comment by TuomoKu** [comment]
Hey, version 1.0.8 introduced an API for triggering, See [http://localhost:5000/api/v1 ](http://localhost:5000/api/v1 )for a list of commands.

I will shortly release a javascript plugin for SPX-GC switch OBS scenes.

**Comment by TuomoKu** [comment]
See section [streaming](https://github.com/TuomoKu/SPX-GC#streaming) in the Readme. Let me know if you need more info.
