### ISSUE TITLE
Cutted text in NAME_LEFT.html

### ISSUE THREAD

**Issue by szymontex** [TuomoKu/SPX-GC#106]
There's lack of delay line in NAME_LEFT.html template that is causing cutting text during playback. It's present in NAME_RIGHT.html and it works properply there. 
```						
                        delay: 0.2, <------
                        width:function(i, target)
                            {
                            target.style.width = "auto"; 
                            var width = target.offsetWidth;
                            target.style.width = "0px"; //now reset it to 0
                            return width; //return the natural height
                            },
```

**Comment by TuomoKu** [comment]
Yup. A "known issue", that the animation sometimes never "completed". The animations in the default templates (1.3.x) have been redone, and is not an issue anymore.
