### ISSUE TITLE
Suggestion: Change Username in the Default Config

### ISSUE THREAD

**Issue by Sevenlive** [TuomoKu/SPX-GC#12]
Hey, thanks for the Application. As someone who builded something lightly simular i really appreciate your effort.
But as i first started to use your Application, i was slightly confused about the "welcome" in the Username Box as i started to set it up. Going though your Source Code i realized you're generating it in the default-Config because you're using it to check if authorization is enabled or not.

But i would suguess changing it to admin rather than welcome and add two labels to the corresponding textboxes. If you would be happy with that, i would be glad to make the changes and add a pull-request.

![image](https://user-images.githubusercontent.com/1346238/103142698-fecb1f80-4707-11eb-9c15-6f4a8dbda525.png)

**Comment by TuomoKu** [comment]
Sounds like a good idea. Please make a PR and I will merge. Thanks for the help!

**Comment by TuomoKu** [comment]
Changed to admin in 1.0.12
