### ISSUE TITLE
Bug: Linux Build is invalid

### ISSUE THREAD

**Issue by Sevenlive** [TuomoKu/SPX-GC#14]
Hey, just want to mention that in the Current Release Version the Linux build is invalid. The Zip-File is corupted. 

I checked it both on a Windows Maschine and on a Linux Maschine.

![image](https://user-images.githubusercontent.com/1346238/103877575-900d9f00-50d5-11eb-800f-baeb7c10c2ff.png)

**Comment by TuomoKu** [comment]
The built process generated invalid zip files, now the packages are updated and should work,
