### ISSUE TITLE
Suggestion: Add runAnimationUPDATE function to spx_cmdhandler.

### ISSUE THREAD

**Issue by timothy02** [TuomoKu/SPX-GC#22]
The template library `spx_cmdhandler.js` should have an optional `runAnimationUPDATE(data)` function fired with `webcg.on('data', ...)` handler. 

That feels like a more natural way to get the variables instead of pulling them out from the HTML like it's done in `SPX1_TICKER_EXCEL.html` right now. 

So instead of doing something like this: 
```javascript
let filename = document.getElementById('f0').innerText;
``` 

you could do something like this:

```javascript
function runAnimationUPDATE(data){
   let filename = data.f0; // Store the value for later usage
}
```

**Comment by TuomoKu** [comment]
I agree, this is not optimal. The current "DOM-approach" stems from compatibility reasons with existing CasparCG templates which use `f0` naming convention in DOM elements for variables. 

Command handler can be (luckily) modified per project or template and should not be considered as a global solution to all templates past, present, and future. Templates may have a need for different event handlers, for instance, next() event call is not required by all templates. Also, some (old) templates require XML data and others JSON data and this adds complexity.

Hopefully one day we have a global handler that can cover all scenarios.

**Comment by TuomoKu** [comment]
The approach mentioned earlier is still valid. Modify cmdhandler / interface as needed per project.
