### ISSUE TITLE
Using chroma key as background

### ISSUE THREAD

**Issue by kmyhre** [TuomoKu/SPX-GC#29]
(moved from Discussions)

Changing `background-color` in `spx_layout.css` (either in `body` or in `.SPXWindow`) or uncommenting `background-image` and redirecting it to `../../../../media/images/bg/chroma.png` apparently works – until you need to have more than one object on screen. This results in the other objects appearing behind the background and thus becoming invisible unless the chroma background is transparent – which would arguably defeat the purpose.

Any suggestions to workarounds? Or – any plans on officially supporting chroma backgrounds?

**Comment by TuomoKu** [comment]
Hey, there is (now) a free **ImageLayer** -template (https://www.spxgc.com/store/ImageLayer-p291331877) which can easily handle images, this is what the chroma.png is there for.

Hope this helps.

**Comment by kmyhre** [comment]
Excellent, thank you!
