### ISSUE TITLE
Incorrect folder paths on MacOS

### ISSUE THREAD

**Issue by TuomoKu** [TuomoKu/SPX-GC#3]
When GC is installed on Mac the DATAROOT-folder and config.json file is generated incorrectly to current user's home directory and not GC's root folder.

Workaround: when running GC for the first time the files and folders will be generated (and the program ends to an error). Close the process, move config.json and DATAROOT-folder to a correct location, modify config.json manually in text editor to the correct filepaths and restart the application.

**Comment by removogel** [comment]
Its the same issue at Linux, config.json and DATAROOT-folder are created in the home folder. After moving it to the application folder i was able to start it and change the paths in the config.

**Comment by TuomoKu** [comment]
Some more findings: 
a) only effects binary package version of SPX-GC
b) The actual issue: Mac defaults to User's home directory (such as `/Users/John` ) when a Terminal is started by **doubleclicking** on any executable shell program. When the same program is started from terminal **prompt** it works _as expected_...

Currently SPX-GC uses `process.cwd()` to get the startup path. Another approach should be taken to figure out if we app is running in pkg environment (on Mac).

**WORKAROUND** until fix: navigate to the install folder with Terminal and start the app there with `.SPX-GC_macos64`command (and NOT by doubleclicking on it)

**Comment by TuomoKu** [comment]
This needs work - the issue is stll present. A textfle added to Mac zip file reading:

> DO NOT DOUBLECLICK SPX-GC_macos64 -file to run it.
> MacOS defaults to "/User/username" -folder when a program is opened by DOUBLECLICKING on it. This WILL CAUSE AN ERROR and default files (config.json, LOG, DATAROOT) will be generated to the home directory and not to the current working directory. Please navigate to the correct folder and start the application with "./SPX-GC_macos64" -command.

**Comment by TuomoKu** [comment]
Fixed in 1.0.12 by introducing a function which checks the runtime environment and returns the path accordingly.
