### ISSUE TITLE
Example Template SPX1 Ticker Sheet Errors

### ISSUE THREAD

**Issue by sledzik1984** [TuomoKu/SPX-GC#30]
Example Template SPX1 Ticker Sheet works ok in Web Playout preview but no in CasparCG.

Tested on CasparCG 2.3.0 LTS and 2.3.2 LTS Beta

In both versions Caspar throws error:

`[2021-03-08 16:43:49.441] [error]   html[http://192.168.15.44:5000/templates/smartpx/Template_Pack_1/SPX1_TICKER_SHEET.html] 1920 1080 50.000000 Log: Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined`

**Comment by TuomoKu** [comment]
Yes, this has come up by other users also. I have a fix for this and will share this in future versions.

**Comment by TuomoKu** [comment]
(closed accidentally)

**Comment by TuomoKu** [comment]
Fixed in an update.
