### ISSUE TITLE
Key/fill out of sync

### ISSUE THREAD

**Issue by primozkikelj** [TuomoKu/SPX-GC#31]
Hello Mr. TuomoKu!

We are a small local TV station and we are currently testing your sw. But unfortunately we faced a small issue, and that is, key/fill are out of sync. We used Blackmagic Decklink Quad 2 video card. Configured outputs in config file with separate key and fill. Outputs from that card are then fed to the Blackmagic Atem video switcher with framestores, but that did not resolve our issues. We assume that the problem arises from that, because we have no reference signal for all video equipment (everything goes to the BM switcher with frame stores). Do you think this coud be the issue? Between key and fill, there is about 5 frames of delay. Thank you for your time and help!

Regards,

Primož Kikelj

**Comment by markusnygard** [comment]
Quad2 has 4 channels that are in sync. If you in Desktop Video Setup split the signals (connector-page) then they can go out of sync, but you get more signals.

**Comment by TuomoKu** [comment]
SPX-GC does not handle key / fill channels "at all" it just renders out a 32bit image with the kind help of a browser and key / fill video processing is done downstream by the video hardware used.

For this reason, there is not much to do with that within SPX-GX itself.

Hopefully,you have found a solution to this.
