### ISSUE TITLE
Renderer layers not playing out correctly on the browser output

### ISSUE THREAD

**Issue by waidis** [TuomoKu/SPX-GC#32]
When using web renderer with specific layers, and rundown items are, for example, on layer 2 and 12, then for some reason, by explicitly choosing layers http://localhost:5000/renderer/?layers=[7,10,12] layer 2 is played out also. Same with layer 3 and 13 and so on.
Using: version 1.0.10 on MacOS BigSur 11.2.3

**Comment by TuomoKu** [comment]
Hey,

I just tested tried this on 1.0.9 and 1.0.10 and I could not replicate this issue. 
There is something you can try to find the reason for this:

- Open renderer URL in browser and open devtools > console
- When a layer (which should not render on that renderer) would print out something like `Commands to layer 16 prevented.` to the console when played from the controller.
- The layer number comes from template > `SPXGCTemplateDefinition.webplayout ` -parameter

Please let me know if this still an issue and I can try to troubleshoot this further.

**Comment by waidis** [comment]
I have tried now with 1.0.11 and still get the same results. If I have layer 2 and 12 and renderer settings ?layers=[12] and play layer 2, I do not get `Commands to layer 2 prevented` as this layer plays out. Only for other layers numbers, it works. For example, `Commands to layer 9 prevented`.

**Comment by TuomoKu** [comment]
I had a closer look now when testing 1.0.12 and sure enough, a clear bug. Thanks for pointing it out. 

Fixed in 1.0.12.
