### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by atscomms** [TuomoKu/SPX-GC#53]
After firing the .exe, I can open the Welcome web page. Going to the Project or Config page kills the process because of an error- operation not permitted... That's about all I can read before it closes.
The new page appears to open but the server has to be restarted.
Here's an error that didn;t close the server window:
2022-02-06T23:54:38.779Z [SPX] error: spx.writeFile - Error while saving: C:\Program Files\SPXGC\config.json: Error: EPERM: operation not permitted, open 'C:\Program Files\SPXGC\config.json'

**Comment by TuomoKu** [comment]
This happens on Windows if:

- SPX is located within `Program Files`-folder
- and the current user does not have Administrative privileges to that folder

This can be fixed by moving SPX to another root folder, such as `C:\SPX\`
