### ISSUE TITLE
How to Update installation

### ISSUE THREAD

**Issue by markusnygard** [TuomoKu/SPX-GC#57]
I would like there to be a way of updating my excisting installation. Now I have to create a new installation (in a new folder) and then do a lot of manual work (renaming/moving files etc) to get  ASSETS and DATAROOT to have the same content and the same links as they had before the update

**Comment by TuomoKu** [comment]
All file references within SPX are relative. So once you have the new version installed, you can copy ASSETS and DATAROOT folders from the old to the new and all your content should work as is.

For DATAROOT-folder there is also an option to have it elsewhere on your filesystem, so it does not need to be within the SPX installation folder structure. This way you will only need to copy ASSETS (templates and media files) to your new installation.

There is a setting in `config.json > general > dataroot` to set the absolute path of the dataroot -folder.
