### ISSUE TITLE
Issue with rundown item duplication

### ISSUE THREAD

**Issue by sarksim** [TuomoKu/SPX-GC#63]
SPX 1.1.0
Win10

Expected behavior: When you click the duplicate icon on a rundown item the item and its properties are copied below the original item and can be edited and played out independently from the original.

Current behavior: When you click the duplicate icon on a rundown item a new "empty" rundown item is created below the original. Playing the "empty" item plays the first item in the rundown.

Steps to reproduce: Download SPX 1.1.0 for Windows 10, unpack and run SPX, open HelloWorld project/My first rundown, duplicate any item on the rundown and play the duplicated item.

**Comment by TuomoKu** [comment]
Fixed in one of the updates.
